package gov.polisen.orm.maps;

import gov.polisen.orm.clients.CaseImageSqlProvider;
import gov.polisen.orm.examples.CaseImageExample;
import gov.polisen.orm.models.CaseImage;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;

public interface CaseImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_images
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @SelectProvider(type=CaseImageSqlProvider.class, method="countByExample")
    int countByExample(CaseImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_images
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @Insert({
        "insert into case_images (image_id, case_id, ",
        "device_id)",
        "values (#{imageId,jdbcType=INTEGER}, #{caseId,jdbcType=INTEGER}, ",
        "#{deviceId,jdbcType=INTEGER})"
    })
    int insert(CaseImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_images
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @InsertProvider(type=CaseImageSqlProvider.class, method="insertSelective")
    int insertSelective(CaseImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_images
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @SelectProvider(type=CaseImageSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="image_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="case_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="device_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<CaseImage> selectByExample(CaseImageExample example);
}