package gov.polisen.orm.maps;

import gov.polisen.orm.clients.CaseSqlProvider;
import gov.polisen.orm.examples.CaseExample;
import gov.polisen.orm.models.Case;
import gov.polisen.orm.models.CaseKey;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;

public interface CaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @SelectProvider(type=CaseSqlProvider.class, method="countByExample")
    int countByExample(CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @Insert({
        "insert into cases (device_id, case_id, ",
        "author, modification_time, ",
        "first_revision_case_id, first_revision_device_id, ",
        "deletion_time, classification, ",
        "status, priority, ",
        "longitude, latitude, time_of_crime, ",
        "description)",
        "values (#{deviceId,jdbcType=INTEGER}, #{caseId,jdbcType=INTEGER}, ",
        "#{author,jdbcType=INTEGER}, #{modificationTime,jdbcType=TIMESTAMP}, ",
        "#{firstRevisionCaseId,jdbcType=INTEGER}, #{firstRevisionDeviceId,jdbcType=INTEGER}, ",
        "#{deletionTime,jdbcType=TIMESTAMP}, #{classification,jdbcType=SMALLINT}, ",
        "#{status,jdbcType=SMALLINT}, #{priority,jdbcType=SMALLINT}, ",
        "#{longitude,jdbcType=REAL}, #{latitude,jdbcType=REAL}, #{timeOfCrime,jdbcType=TIMESTAMP}, ",
        "#{description,jdbcType=VARCHAR})"
    })
    int insert(Case record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @InsertProvider(type=CaseSqlProvider.class, method="insertSelective")
    int insertSelective(Case record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @SelectProvider(type=CaseSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="device_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="case_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="author", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="modification_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="first_revision_case_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="first_revision_device_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="deletion_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="classification", javaType=Short.class, jdbcType=JdbcType.SMALLINT),
        @Arg(column="status", javaType=Short.class, jdbcType=JdbcType.SMALLINT),
        @Arg(column="priority", javaType=Short.class, jdbcType=JdbcType.SMALLINT),
        @Arg(column="longitude", javaType=Float.class, jdbcType=JdbcType.REAL),
        @Arg(column="latitude", javaType=Float.class, jdbcType=JdbcType.REAL),
        @Arg(column="time_of_crime", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="description", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Case> selectByExample(CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @Select({
        "select",
        "device_id, case_id, author, modification_time, first_revision_case_id, first_revision_device_id, ",
        "deletion_time, classification, status, priority, longitude, latitude, time_of_crime, ",
        "description",
        "from cases",
        "where device_id = #{deviceId,jdbcType=INTEGER}",
          "and case_id = #{caseId,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="device_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="case_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="author", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="modification_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="first_revision_case_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="first_revision_device_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="deletion_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="classification", javaType=Short.class, jdbcType=JdbcType.SMALLINT),
        @Arg(column="status", javaType=Short.class, jdbcType=JdbcType.SMALLINT),
        @Arg(column="priority", javaType=Short.class, jdbcType=JdbcType.SMALLINT),
        @Arg(column="longitude", javaType=Float.class, jdbcType=JdbcType.REAL),
        @Arg(column="latitude", javaType=Float.class, jdbcType=JdbcType.REAL),
        @Arg(column="time_of_crime", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="description", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Case selectByPrimaryKey(CaseKey key);
}