package gov.polisen.orm.maps;

import gov.polisen.orm.clients.PermissionsOnDeploymentSqlProvider;
import gov.polisen.orm.examples.PermissionsOnDeploymentExample;
import gov.polisen.orm.models.PermissionsOnDeployment;
import gov.polisen.orm.models.PermissionsOnDeploymentKey;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PermissionsOnDeploymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @SelectProvider(type=PermissionsOnDeploymentSqlProvider.class, method="countByExample")
    int countByExample(PermissionsOnDeploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @DeleteProvider(type=PermissionsOnDeploymentSqlProvider.class, method="deleteByExample")
    int deleteByExample(PermissionsOnDeploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @Delete({
        "delete from permissions_on_deployments",
        "where deployment_id = #{deploymentId,jdbcType=INTEGER}",
          "and user_id = #{userId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(PermissionsOnDeploymentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @Insert({
        "insert into permissions_on_deployments (deployment_id, user_id, ",
        "read, add_data, modify, ",
        "change_permissions)",
        "values (#{deploymentId,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{read,jdbcType=BIT}, #{addData,jdbcType=BIT}, #{modify,jdbcType=BIT}, ",
        "#{changePermissions,jdbcType=BIT})"
    })
    int insert(PermissionsOnDeployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @InsertProvider(type=PermissionsOnDeploymentSqlProvider.class, method="insertSelective")
    int insertSelective(PermissionsOnDeployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @SelectProvider(type=PermissionsOnDeploymentSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="deployment_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="user_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="read", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="add_data", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="modify", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="change_permissions", javaType=Boolean.class, jdbcType=JdbcType.BIT)
    })
    List<PermissionsOnDeployment> selectByExample(PermissionsOnDeploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @Select({
        "select",
        "deployment_id, user_id, read, add_data, modify, change_permissions",
        "from permissions_on_deployments",
        "where deployment_id = #{deploymentId,jdbcType=INTEGER}",
          "and user_id = #{userId,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="deployment_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="user_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="read", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="add_data", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="modify", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="change_permissions", javaType=Boolean.class, jdbcType=JdbcType.BIT)
    })
    PermissionsOnDeployment selectByPrimaryKey(PermissionsOnDeploymentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @UpdateProvider(type=PermissionsOnDeploymentSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PermissionsOnDeployment record, @Param("example") PermissionsOnDeploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @UpdateProvider(type=PermissionsOnDeploymentSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PermissionsOnDeployment record, @Param("example") PermissionsOnDeploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @UpdateProvider(type=PermissionsOnDeploymentSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PermissionsOnDeployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @Update({
        "update permissions_on_deployments",
        "set read = #{read,jdbcType=BIT},",
          "add_data = #{addData,jdbcType=BIT},",
          "modify = #{modify,jdbcType=BIT},",
          "change_permissions = #{changePermissions,jdbcType=BIT}",
        "where deployment_id = #{deploymentId,jdbcType=INTEGER}",
          "and user_id = #{userId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PermissionsOnDeployment record);
}