package gov.polisen.orm.maps;

import gov.polisen.orm.clients.PermissionsOnCaseSqlProvider;
import gov.polisen.orm.examples.PermissionsOnCaseExample;
import gov.polisen.orm.models.PermissionsOnCase;
import gov.polisen.orm.models.PermissionsOnCaseKey;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PermissionsOnCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @SelectProvider(type=PermissionsOnCaseSqlProvider.class, method="countByExample")
    int countByExample(PermissionsOnCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @DeleteProvider(type=PermissionsOnCaseSqlProvider.class, method="deleteByExample")
    int deleteByExample(PermissionsOnCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @Delete({
        "delete from permissions_on_cases",
        "where device_id = #{deviceId,jdbcType=INTEGER}",
          "and case_id = #{caseId,jdbcType=INTEGER}",
          "and user_id = #{userId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(PermissionsOnCaseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @Insert({
        "insert into permissions_on_cases (device_id, case_id, ",
        "user_id, read, add_data, ",
        "modify, change_permissions)",
        "values (#{deviceId,jdbcType=INTEGER}, #{caseId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{read,jdbcType=BIT}, #{addData,jdbcType=BIT}, ",
        "#{modify,jdbcType=BIT}, #{changePermissions,jdbcType=BIT})"
    })
    int insert(PermissionsOnCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @InsertProvider(type=PermissionsOnCaseSqlProvider.class, method="insertSelective")
    int insertSelective(PermissionsOnCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @SelectProvider(type=PermissionsOnCaseSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="device_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="case_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="user_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="read", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="add_data", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="modify", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="change_permissions", javaType=Boolean.class, jdbcType=JdbcType.BIT)
    })
    List<PermissionsOnCase> selectByExample(PermissionsOnCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @Select({
        "select",
        "device_id, case_id, user_id, read, add_data, modify, change_permissions",
        "from permissions_on_cases",
        "where device_id = #{deviceId,jdbcType=INTEGER}",
          "and case_id = #{caseId,jdbcType=INTEGER}",
          "and user_id = #{userId,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="device_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="case_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="user_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="read", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="add_data", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="modify", javaType=Boolean.class, jdbcType=JdbcType.BIT),
        @Arg(column="change_permissions", javaType=Boolean.class, jdbcType=JdbcType.BIT)
    })
    PermissionsOnCase selectByPrimaryKey(PermissionsOnCaseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @UpdateProvider(type=PermissionsOnCaseSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PermissionsOnCase record, @Param("example") PermissionsOnCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @UpdateProvider(type=PermissionsOnCaseSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PermissionsOnCase record, @Param("example") PermissionsOnCaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @UpdateProvider(type=PermissionsOnCaseSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PermissionsOnCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    @Update({
        "update permissions_on_cases",
        "set read = #{read,jdbcType=BIT},",
          "add_data = #{addData,jdbcType=BIT},",
          "modify = #{modify,jdbcType=BIT},",
          "change_permissions = #{changePermissions,jdbcType=BIT}",
        "where device_id = #{deviceId,jdbcType=INTEGER}",
          "and case_id = #{caseId,jdbcType=INTEGER}",
          "and user_id = #{userId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PermissionsOnCase record);
}