package gov.polisen.orm.examples;

import java.util.ArrayList;
import java.util.List;

public class PermissionsOnDeploymentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public PermissionsOnDeploymentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDeploymentIdIsNull() {
            addCriterion("deployment_id is null");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdIsNotNull() {
            addCriterion("deployment_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdEqualTo(Integer value) {
            addCriterion("deployment_id =", value, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdNotEqualTo(Integer value) {
            addCriterion("deployment_id <>", value, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdGreaterThan(Integer value) {
            addCriterion("deployment_id >", value, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("deployment_id >=", value, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdLessThan(Integer value) {
            addCriterion("deployment_id <", value, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdLessThanOrEqualTo(Integer value) {
            addCriterion("deployment_id <=", value, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdIn(List<Integer> values) {
            addCriterion("deployment_id in", values, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdNotIn(List<Integer> values) {
            addCriterion("deployment_id not in", values, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdBetween(Integer value1, Integer value2) {
            addCriterion("deployment_id between", value1, value2, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andDeploymentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("deployment_id not between", value1, value2, "deploymentId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andReadIsNull() {
            addCriterion("read is null");
            return (Criteria) this;
        }

        public Criteria andReadIsNotNull() {
            addCriterion("read is not null");
            return (Criteria) this;
        }

        public Criteria andReadEqualTo(Boolean value) {
            addCriterion("read =", value, "read");
            return (Criteria) this;
        }

        public Criteria andReadNotEqualTo(Boolean value) {
            addCriterion("read <>", value, "read");
            return (Criteria) this;
        }

        public Criteria andReadGreaterThan(Boolean value) {
            addCriterion("read >", value, "read");
            return (Criteria) this;
        }

        public Criteria andReadGreaterThanOrEqualTo(Boolean value) {
            addCriterion("read >=", value, "read");
            return (Criteria) this;
        }

        public Criteria andReadLessThan(Boolean value) {
            addCriterion("read <", value, "read");
            return (Criteria) this;
        }

        public Criteria andReadLessThanOrEqualTo(Boolean value) {
            addCriterion("read <=", value, "read");
            return (Criteria) this;
        }

        public Criteria andReadIn(List<Boolean> values) {
            addCriterion("read in", values, "read");
            return (Criteria) this;
        }

        public Criteria andReadNotIn(List<Boolean> values) {
            addCriterion("read not in", values, "read");
            return (Criteria) this;
        }

        public Criteria andReadBetween(Boolean value1, Boolean value2) {
            addCriterion("read between", value1, value2, "read");
            return (Criteria) this;
        }

        public Criteria andReadNotBetween(Boolean value1, Boolean value2) {
            addCriterion("read not between", value1, value2, "read");
            return (Criteria) this;
        }

        public Criteria andAddDataIsNull() {
            addCriterion("add_data is null");
            return (Criteria) this;
        }

        public Criteria andAddDataIsNotNull() {
            addCriterion("add_data is not null");
            return (Criteria) this;
        }

        public Criteria andAddDataEqualTo(Boolean value) {
            addCriterion("add_data =", value, "addData");
            return (Criteria) this;
        }

        public Criteria andAddDataNotEqualTo(Boolean value) {
            addCriterion("add_data <>", value, "addData");
            return (Criteria) this;
        }

        public Criteria andAddDataGreaterThan(Boolean value) {
            addCriterion("add_data >", value, "addData");
            return (Criteria) this;
        }

        public Criteria andAddDataGreaterThanOrEqualTo(Boolean value) {
            addCriterion("add_data >=", value, "addData");
            return (Criteria) this;
        }

        public Criteria andAddDataLessThan(Boolean value) {
            addCriterion("add_data <", value, "addData");
            return (Criteria) this;
        }

        public Criteria andAddDataLessThanOrEqualTo(Boolean value) {
            addCriterion("add_data <=", value, "addData");
            return (Criteria) this;
        }

        public Criteria andAddDataIn(List<Boolean> values) {
            addCriterion("add_data in", values, "addData");
            return (Criteria) this;
        }

        public Criteria andAddDataNotIn(List<Boolean> values) {
            addCriterion("add_data not in", values, "addData");
            return (Criteria) this;
        }

        public Criteria andAddDataBetween(Boolean value1, Boolean value2) {
            addCriterion("add_data between", value1, value2, "addData");
            return (Criteria) this;
        }

        public Criteria andAddDataNotBetween(Boolean value1, Boolean value2) {
            addCriterion("add_data not between", value1, value2, "addData");
            return (Criteria) this;
        }

        public Criteria andModifyIsNull() {
            addCriterion("modify is null");
            return (Criteria) this;
        }

        public Criteria andModifyIsNotNull() {
            addCriterion("modify is not null");
            return (Criteria) this;
        }

        public Criteria andModifyEqualTo(Boolean value) {
            addCriterion("modify =", value, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyNotEqualTo(Boolean value) {
            addCriterion("modify <>", value, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyGreaterThan(Boolean value) {
            addCriterion("modify >", value, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyGreaterThanOrEqualTo(Boolean value) {
            addCriterion("modify >=", value, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyLessThan(Boolean value) {
            addCriterion("modify <", value, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyLessThanOrEqualTo(Boolean value) {
            addCriterion("modify <=", value, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyIn(List<Boolean> values) {
            addCriterion("modify in", values, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyNotIn(List<Boolean> values) {
            addCriterion("modify not in", values, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyBetween(Boolean value1, Boolean value2) {
            addCriterion("modify between", value1, value2, "modify");
            return (Criteria) this;
        }

        public Criteria andModifyNotBetween(Boolean value1, Boolean value2) {
            addCriterion("modify not between", value1, value2, "modify");
            return (Criteria) this;
        }

        public Criteria andChangePermissionsIsNull() {
            addCriterion("change_permissions is null");
            return (Criteria) this;
        }

        public Criteria andChangePermissionsIsNotNull() {
            addCriterion("change_permissions is not null");
            return (Criteria) this;
        }

        public Criteria andChangePermissionsEqualTo(Boolean value) {
            addCriterion("change_permissions =", value, "changePermissions");
            return (Criteria) this;
        }

        public Criteria andChangePermissionsNotEqualTo(Boolean value) {
            addCriterion("change_permissions <>", value, "changePermissions");
            return (Criteria) this;
        }

        public Criteria andChangePermissionsGreaterThan(Boolean value) {
            addCriterion("change_permissions >", value, "changePermissions");
            return (Criteria) this;
        }

        public Criteria andChangePermissionsGreaterThanOrEqualTo(Boolean value) {
            addCriterion("change_permissions >=", value, "changePermissions");
            return (Criteria) this;
        }

        public Criteria andChangePermissionsLessThan(Boolean value) {
            addCriterion("change_permissions <", value, "changePermissions");
            return (Criteria) this;
        }

        public Criteria andChangePermissionsLessThanOrEqualTo(Boolean value) {
            addCriterion("change_permissions <=", value, "changePermissions");
            return (Criteria) this;
        }

        public Criteria andChangePermissionsIn(List<Boolean> values) {
            addCriterion("change_permissions in", values, "changePermissions");
            return (Criteria) this;
        }

        public Criteria andChangePermissionsNotIn(List<Boolean> values) {
            addCriterion("change_permissions not in", values, "changePermissions");
            return (Criteria) this;
        }

        public Criteria andChangePermissionsBetween(Boolean value1, Boolean value2) {
            addCriterion("change_permissions between", value1, value2, "changePermissions");
            return (Criteria) this;
        }

        public Criteria andChangePermissionsNotBetween(Boolean value1, Boolean value2) {
            addCriterion("change_permissions not between", value1, value2, "changePermissions");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 25 17:12:46 CEST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}