package gov.polisen.orm.models;

public class CaseImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_images.image_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_images.case_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_images.device_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer deviceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_images
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public CaseImage(Integer imageId, Integer caseId, Integer deviceId) {
        this.imageId = imageId;
        this.caseId = caseId;
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_images.image_id
     *
     * @return the value of case_images.image_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_images.case_id
     *
     * @return the value of case_images.case_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_images.device_id
     *
     * @return the value of case_images.device_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getDeviceId() {
        return deviceId;
    }
}