package gov.polisen.orm.models;

public class CaseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.device_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.case_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer caseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public CaseKey(Integer deviceId, Integer caseId) {
        this.deviceId = deviceId;
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.device_id
     *
     * @return the value of cases.device_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.case_id
     *
     * @return the value of cases.case_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getCaseId() {
        return caseId;
    }
}