package gov.polisen.orm.models;

import java.util.Date;

public class Case extends CaseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.author
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.modification_time
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Date modificationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.first_revision_case_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer firstRevisionCaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.first_revision_device_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer firstRevisionDeviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.deletion_time
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Date deletionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.classification
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Short classification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.status
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.priority
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Short priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.longitude
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Float longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.latitude
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Float latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.time_of_crime
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Date timeOfCrime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.description
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Case(Integer deviceId, Integer caseId, Integer author, Date modificationTime, Integer firstRevisionCaseId, Integer firstRevisionDeviceId, Date deletionTime, Short classification, Short status, Short priority, Float longitude, Float latitude, Date timeOfCrime, String description) {
        super(deviceId, caseId);
        this.author = author;
        this.modificationTime = modificationTime;
        this.firstRevisionCaseId = firstRevisionCaseId;
        this.firstRevisionDeviceId = firstRevisionDeviceId;
        this.deletionTime = deletionTime;
        this.classification = classification;
        this.status = status;
        this.priority = priority;
        this.longitude = longitude;
        this.latitude = latitude;
        this.timeOfCrime = timeOfCrime;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.author
     *
     * @return the value of cases.author
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.modification_time
     *
     * @return the value of cases.modification_time
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Date getModificationTime() {
        return modificationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.first_revision_case_id
     *
     * @return the value of cases.first_revision_case_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getFirstRevisionCaseId() {
        return firstRevisionCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.first_revision_device_id
     *
     * @return the value of cases.first_revision_device_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getFirstRevisionDeviceId() {
        return firstRevisionDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.deletion_time
     *
     * @return the value of cases.deletion_time
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Date getDeletionTime() {
        return deletionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.classification
     *
     * @return the value of cases.classification
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Short getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.status
     *
     * @return the value of cases.status
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.priority
     *
     * @return the value of cases.priority
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Short getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.longitude
     *
     * @return the value of cases.longitude
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.latitude
     *
     * @return the value of cases.latitude
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.time_of_crime
     *
     * @return the value of cases.time_of_crime
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Date getTimeOfCrime() {
        return timeOfCrime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.description
     *
     * @return the value of cases.description
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public String getDescription() {
        return description;
    }
}