package gov.polisen.orm.models;

public class Classification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classifications.id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classifications.shorthand
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private String shorthand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classifications.description
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classifications
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Classification(Short id, String shorthand, String description) {
        this.id = id;
        this.shorthand = shorthand;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classifications.id
     *
     * @return the value of classifications.id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classifications.shorthand
     *
     * @return the value of classifications.shorthand
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public String getShorthand() {
        return shorthand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classifications.description
     *
     * @return the value of classifications.description
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public String getDescription() {
        return description;
    }
}