package gov.polisen.orm.models;

public class DeploymentImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploymentimages.imageid
     *
     * @mbggenerated Wed Apr 09 16:26:54 CEST 2014
     */
    private Integer imageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploymentimages.deploymentid
     *
     * @mbggenerated Wed Apr 09 16:26:54 CEST 2014
     */
    private Integer deploymentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploymentimages
     *
     * @mbggenerated Wed Apr 09 16:26:54 CEST 2014
     */
    public DeploymentImage(Integer imageid, Integer deploymentid) {
        this.imageid = imageid;
        this.deploymentid = deploymentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploymentimages.imageid
     *
     * @return the value of deploymentimages.imageid
     *
     * @mbggenerated Wed Apr 09 16:26:54 CEST 2014
     */
    public Integer getImageid() {
        return imageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploymentimages.deploymentid
     *
     * @return the value of deploymentimages.deploymentid
     *
     * @mbggenerated Wed Apr 09 16:26:54 CEST 2014
     */
    public Integer getDeploymentid() {
        return deploymentid;
    }
}