package gov.polisen.orm.models;

import java.util.Date;

public class Deployment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployments.id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployments.author
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployments.modification_time
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Date modificationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployments.first_revision
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer firstRevision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployments.deletion_time
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Date deletionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployments.status
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployments.priority
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Short priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployments.longitude
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Float longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployments.latitude
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Float latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployments.description
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Deployment(Integer id, Integer author, Date modificationTime, Integer firstRevision, Date deletionTime, Short status, Short priority, Float longitude, Float latitude, String description) {
        this.id = id;
        this.author = author;
        this.modificationTime = modificationTime;
        this.firstRevision = firstRevision;
        this.deletionTime = deletionTime;
        this.status = status;
        this.priority = priority;
        this.longitude = longitude;
        this.latitude = latitude;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployments.id
     *
     * @return the value of deployments.id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployments.author
     *
     * @return the value of deployments.author
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployments.modification_time
     *
     * @return the value of deployments.modification_time
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Date getModificationTime() {
        return modificationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployments.first_revision
     *
     * @return the value of deployments.first_revision
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getFirstRevision() {
        return firstRevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployments.deletion_time
     *
     * @return the value of deployments.deletion_time
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Date getDeletionTime() {
        return deletionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployments.status
     *
     * @return the value of deployments.status
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployments.priority
     *
     * @return the value of deployments.priority
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Short getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployments.longitude
     *
     * @return the value of deployments.longitude
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployments.latitude
     *
     * @return the value of deployments.latitude
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployments.description
     *
     * @return the value of deployments.description
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public String getDescription() {
        return description;
    }
}