package gov.polisen.orm.models;

import java.util.Date;

public class Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devices.id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devices.last_seen
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Date lastSeen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devices.battery
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Short battery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devices.longitude
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Float longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devices.latitude
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Float latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devices.ip
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devices
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Device(Integer id, Date lastSeen, Short battery, Float longitude, Float latitude, String ip) {
        this.id = id;
        this.lastSeen = lastSeen;
        this.battery = battery;
        this.longitude = longitude;
        this.latitude = latitude;
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devices.id
     *
     * @return the value of devices.id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devices.last_seen
     *
     * @return the value of devices.last_seen
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Date getLastSeen() {
        return lastSeen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devices.battery
     *
     * @return the value of devices.battery
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Short getBattery() {
        return battery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devices.longitude
     *
     * @return the value of devices.longitude
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devices.latitude
     *
     * @return the value of devices.latitude
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devices.ip
     *
     * @return the value of devices.ip
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public String getIp() {
        return ip;
    }
}