package gov.polisen.orm.models;

public class PermissionsOnCaseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionsoncases.deviceid
     *
     * @mbggenerated Wed Apr 09 16:26:54 CEST 2014
     */
    private Integer deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionsoncases.caseid
     *
     * @mbggenerated Wed Apr 09 16:26:54 CEST 2014
     */
    private Integer caseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionsoncases.userid
     *
     * @mbggenerated Wed Apr 09 16:26:54 CEST 2014
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionsoncases
     *
     * @mbggenerated Wed Apr 09 16:26:54 CEST 2014
     */
    public PermissionsOnCaseKey(Integer deviceid, Integer caseid, Integer userid) {
        this.deviceid = deviceid;
        this.caseid = caseid;
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionsoncases.deviceid
     *
     * @return the value of permissionsoncases.deviceid
     *
     * @mbggenerated Wed Apr 09 16:26:54 CEST 2014
     */
    public Integer getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionsoncases.caseid
     *
     * @return the value of permissionsoncases.caseid
     *
     * @mbggenerated Wed Apr 09 16:26:54 CEST 2014
     */
    public Integer getCaseid() {
        return caseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionsoncases.userid
     *
     * @return the value of permissionsoncases.userid
     *
     * @mbggenerated Wed Apr 09 16:26:54 CEST 2014
     */
    public Integer getUserid() {
        return userid;
    }
}