package gov.polisen.orm.models;

public class PermissionsOnCaseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions_on_cases.device_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions_on_cases.case_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions_on_cases.user_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_cases
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public PermissionsOnCaseKey(Integer deviceId, Integer caseId, Integer userId) {
        this.deviceId = deviceId;
        this.caseId = caseId;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions_on_cases.device_id
     *
     * @return the value of permissions_on_cases.device_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions_on_cases.case_id
     *
     * @return the value of permissions_on_cases.case_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions_on_cases.user_id
     *
     * @return the value of permissions_on_cases.user_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getUserId() {
        return userId;
    }
}