package gov.polisen.orm.models;

public class PermissionsOnDeploymentKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions_on_deployments.deployment_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer deploymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions_on_deployments.user_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public PermissionsOnDeploymentKey(Integer deploymentId, Integer userId) {
        this.deploymentId = deploymentId;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions_on_deployments.deployment_id
     *
     * @return the value of permissions_on_deployments.deployment_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getDeploymentId() {
        return deploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions_on_deployments.user_id
     *
     * @return the value of permissions_on_deployments.user_id
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Integer getUserId() {
        return userId;
    }
}