package gov.polisen.orm.models;

public class PermissionsOnDeployment extends PermissionsOnDeploymentKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions_on_deployments.read
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Boolean read;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions_on_deployments.add_data
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Boolean addData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions_on_deployments.modify
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Boolean modify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions_on_deployments.change_permissions
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    private Boolean changePermissions;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions_on_deployments
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public PermissionsOnDeployment(Integer deploymentId, Integer userId, Boolean read, Boolean addData, Boolean modify, Boolean changePermissions) {
        super(deploymentId, userId);
        this.read = read;
        this.addData = addData;
        this.modify = modify;
        this.changePermissions = changePermissions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions_on_deployments.read
     *
     * @return the value of permissions_on_deployments.read
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Boolean getRead() {
        return read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions_on_deployments.add_data
     *
     * @return the value of permissions_on_deployments.add_data
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Boolean getAddData() {
        return addData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions_on_deployments.modify
     *
     * @return the value of permissions_on_deployments.modify
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Boolean getModify() {
        return modify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions_on_deployments.change_permissions
     *
     * @return the value of permissions_on_deployments.change_permissions
     *
     * @mbggenerated Fri Apr 25 17:12:46 CEST 2014
     */
    public Boolean getChangePermissions() {
        return changePermissions;
    }
}